#pragma classflags ("forceupdate")
#pragma namespace ( "\\\\.\\Root\\Microsoft\\Windows\\DeliveryOptimization")

#pragma deleteclass("MSFT_DOBaseStatus",nofail)
#pragma deleteclass("MSFT_DOCurrentStatus",nofail)
#pragma deleteclass("MSFT_DODownloadUsage",nofail)
#pragma deleteclass("MSFT_DOUploadUsage",nofail)
#pragma deleteclass("MSFT_DOUsage",nofail)
#pragma deleteclass("MSFT_DeliveryOptimizationConfig",nofail)
#pragma deleteclass("MSFT_DeliveryOptimizationExtendedConfig",nofail)
#pragma deleteclass("MSFT_DeliveryOptimizationFile",nofail)
#pragma deleteclass("MSFT_DeliveryOptimizationFilePeerInfo",nofail)
#pragma deleteinstance("__InstanceProviderRegistration.Provider=\"\\\\\\\\.\\\\root\\\\Microsoft\\\\Windows\\\\DeliveryOptimization:__Win32Provider.Name=\\\"DeliveryOptimizationMIProv\\\"\"", nofail)
#pragma deleteinstance("__Win32Provider.Name=\"DeliveryOptimizationMIProv\"", nofail)
